# Generated by Django 3.0.5 on 2024-02-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_files_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='file_path',
            field=models.TextField(),
        ),
    ]
