# Generated by Django 3.0.5 on 2024-02-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_files_backend_app', '0002_auto_20240222_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
