# Generated by Django 5.2 on 2025-04-23 07:10

import s3app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3app', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, validators=[s3app.models.validate_not_forbidden_name]),
        ),
    ]
